CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    default_currency TEXT NOT NULL
);

CREATE UNIQUE INDEX uq_users_email_lower
    ON users (lower(email));
